# Welcome to numpy

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,32,7]],np.int8) #array creation using list

In [3]:
myarr

array([[ 3,  6, 32,  7]], dtype=int8)

In [4]:
myarr[0,1]

6

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr.dtype

dtype('int8')

In [7]:
myarr[0,2]=8

# Conversion from other Python Structure

In [8]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
listarray.shape

(3, 3)

In [11]:
listarray.dtype

dtype('int64')

In [12]:
listarray.size

9

In [13]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [14]:
zeros = np.zeros((2,5))

In [15]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
zeros.shape

(2, 5)

In [17]:
zeros.dtype

dtype('float64')

In [18]:
zeros.size

10

In [19]:
rng = np.arange(15)

In [20]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
lspace = np.linspace(1,4,4)

In [24]:
lspace

array([1., 2., 3., 4.])

In [27]:
emp = np.empty((4,6))

In [28]:
emp

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [29]:
emp_like = np.empty_like(lspace)

In [30]:
emp_like

array([1., 2., 3., 4.])

In [31]:
ide = np.identity(45)

In [32]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [33]:
ide.shape

(45, 45)

In [34]:
ide.size

2025

In [35]:
ide.dtype

dtype('float64')

In [36]:
eye = np.eye(4)

In [37]:
eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
arr = np.arange(99)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [40]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [42]:
arr = arr.reshape(11,9)

In [43]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80],
       [81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [44]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [48]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)

In [49]:
ar.sum(axis=0)

array([12,  8,  9])

In [50]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [51]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [52]:
ar.flat

In [53]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [54]:
ar.ndim

2

In [55]:
ar.size

9

In [56]:
ar.nbytes

72

In [57]:
one = np.array([1,3,4,63,2])

# Prints indices and it 

In [58]:
one.argmax()

3

In [59]:
ar.argmin()

8

In [60]:
one.argsort()

array([0, 4, 1, 2, 3])

In [61]:
ar.argmax(axis=0)

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


array([2, 1, 1])

In [62]:
ar.argmax(axis=1)

array([2, 2, 0])

In [63]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [64]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [65]:
ar.ndim

2

In [66]:
ar = ar.reshape(1,9)

In [67]:
ar

array([[1, 2, 3, 4, 5, 6, 7, 1, 0]])

In [68]:
ar.ndim

2

In [74]:
ar2 = np.array([[1,2,1],[4,0,6],[8,1,0]])
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [73]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [71]:
ar=ar.reshape(3,3)

In [72]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [75]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [76]:
ar-ar2

array([[ 0,  0,  2],
       [ 0,  5,  0],
       [-1,  0,  0]])

In [77]:
ar.max()

7

In [78]:
ar.min()

0

In [82]:
np.where(ar>5)


(array([1, 2]), array([2, 0]))

In [83]:
type(np.where(ar>5))


tuple

In [84]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [85]:
np.count_nonzero(ar)

8

In [86]:
ar[1,2]=0

In [87]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))

In [88]:
import sys

In [89]:
py_ar = [0,4,55,2]

In [90]:
np_ar = np.array(py_ar)

In [91]:
sys.getsizeof(1)*len(py_ar)

112

In [92]:
np_ar.itemsize*np_ar.size

32

In [95]:
np.mean(ar)

2.5555555555555554